- hosts: ubuntu
  become: yes
  tasks:
    - name: Ensure apache installed
      apt:
        name: apache2
        state: present
    - name: Ensure that apache is running and will be started on boot
      service:
        name: apache2
        state: started
        enabled: yes    