---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages
    apt:
      update_cache: yes
  - name: install apache
    apt:
      name: apache2
      state: present
  - name: create home page
    file: 
      path: /var/www/ansible/index.html 
      state: file 
  - name: stop apache
    service:
      name: apache2
      state: stopped
  - name: copy the home page to server
    file:
      src: /home/ansible/index.html
      dest: /var/www/html/index.html
  - name: start the apache
    service:
      name: apche2
      start: started        
