---
- hosts: ubuntu
  vars:
    package: tomcat
    st_to_be_set: absent
  become: yes
  tasks:
  - name: "update apt repo"
    apt:
      update_cache: yes
  - name: install tomcat
    apt:
      name: "{{ package }}"
      state: "{{ st_to_be_set }}"
    notify:
      restart tomcat
  handlers:
  - name: restart tomcat
    service:
      name: "{{ package }}"
      state: restarted
    when: st_to_be_set == "present"          